config/routes.rb
# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'users/registrations', sessions: 'users/sessions' }

  devise_scope :user do
    get '/users', to: 'devise/registrations#new'
    get '/users/password', to: 'devise/passwords#new'
  end

  root 'tests#index'

  # devise_for :users, path: :gurus, path_names: { sign_in: :login, sign_out: :logout }

  resources :tests, only: :index do
    resources :questions, shallow: true, only: :show do
      resources :answers, shallow: true, only: :show
    end

    member do
      post :start
    end
  end

  resources :results, only: %i[show update] do
    member do
      get :result
    end
  end

  resources :gists, only: :create

  namespace :admin do
    resources :tests do
      patch :update_inline, on: :member
      resources :questions, shallow: true, except: %i[index] do
        resources :answers, shallow: true, except: %i[index]
      end
    end
    resources :gists, only: :index

    resources :badges, except: %i[show]

    resources :achievements, only: %i[index create new] do
      collection do
        get :show_user_achieved
      end
    end
  end

  resources :badges, only: %i[index]

  resources :feedbacks, only: %i[new create]

  resources :achievements, only: :index
end

app/views/admin/_tip.html.erb
<nav class="navbar navbar-expand-sm navbar-light bg-light">
  <div class="container-fluid d-flex">

    <%= link_to "Project TetsGuru", root_path, class: 'navbar-brand' %> 
    <% if user_signed_in? && current_user.admin? %>     
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarID"
        aria-controls="navbarID" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarID">
      <ul class="navbar-nav flex-grow-1">
        <li class="nav-item">
          <a class="nav-link" href=<%= admin_tests_path %>><%= t('.list') %></a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href=<%= new_admin_test_path %> ><%= t('.create') %></a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href=<%= admin_badges_path %>><%= t('.badge') %></a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href= <%=admin_achievements_path%>><%= t('.achieve') %></a>        
        </li>
        <li class="nav-item">
          <a class="nav-link" href=<%= admin_gists_path %>><%= t('.gists') %></a>
        </li>
      </ul>  
      
        <strong class="position-absolute top-50 start-50 translate-middle"><%= t('.panel') %></strong>  
      <% end %>
    </div>

    <div class="container d-flex justify-content-end col-4">
      <% if user_signed_in? %>
        <strong class="position-absolute top-50 translate-middle col-2">
        <%= t('.welcome', user: current_user.name.capitalize )%> |
        </strong>
      <% end %>

      <ul class="navbar-nav">   
       <li class="nav-item<%= " active" if I18n.locale == :ru %>" >
           <%= link_to "Рус", { lang: :ru }, class: "nav-link" %>     
        </li>
        <li class="nav-item<%= " active" if I18n.locale == :en %>" >
          <%= link_to "En", { lang: :en }, class: "nav-link" %>     
        </li>
        <li class="nav-item">
          <%= link_to t('.logout'), destroy_user_session_path, class: "nav-link", method: :delete %>
        </li>
      </ul>
    <div>
 
 

   
  </div>
</nav>