config/routes.rb
# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'users/registrations', sessions: 'users/sessions' }

  devise_scope :user do
    get '/users', to: 'devise/registrations#new'
    get '/users/password', to: 'devise/passwords#new'
  end

  root 'tests#index'

  # devise_for :users, path: :gurus, path_names: { sign_in: :login, sign_out: :logout }

  resources :tests, only: :index do
    resources :questions, shallow: true, only: :show do
      resources :answers, shallow: true, only: :show
    end

    member do
      post :start
    end
  end

  resources :results, only: %i[show update] do
    member do
      get :result
    end
  end

  resources :gists, only: :create

  namespace :admin do
    resources :tests do
      patch :update_inline, on: :member
      resources :questions, shallow: true, except: %i[index] do
        resources :answers, shallow: true, except: %i[index]
      end
    end
    resources :gists, only: :index

    resources :badges, except: %i[show]

    resources :achievements, only: %i[index create new] do
      collection do
        get :show_user_achieved
      end
    end
  end

  resources :badges, only: %i[index]

  resources :feedbacks, only: %i[new create]

  resources :achievements, only: :index
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :test

  has_many :answers, dependent: :destroy
  has_many :gist, dependent: :destroy

  validates :body, presence: true
end

app/models/result.rb
class Result < ApplicationRecord
  SUCCESS_RATIO = 85

  belongs_to :user
  belongs_to :test
  belongs_to :current_question, class_name: 'Question', optional: true

  before_validation :before_validation_set_current_question, on: %i[create update]

  def accept!(answer_ids)
    self.correct_questions += 1 if correct_answer?(answer_ids)
    self.success = true if successful?
    current_question = nil if time_out?

    save!
  end

  def complited?
    current_question.nil?
  end

  def number_question
    test.questions.index(current_question) + 1
  end

  def successful?
    percentage_result > SUCCESS_RATIO
  end

  def percentage_result
    (self.correct_questions * 100 / test.questions.count.to_f).round(2)
  end

  def test_category_id
    test.category_id
  end

  def test_level
    test.level
  end

  def list_tests_success
    user.tests.where(results: { success: true })
  end

  def time_limit
    test.time_limit
  end

  def time_left
    (created_at - Time.current).round + test.time_limit
  end

  private

  def before_validation_set_current_question
    self.current_question = next_question
  end

  def correct_answer?(answer_ids)
    correct_answers.ids.sort == answer_ids.to_a.map(&:to_i).sort
  end

  def correct_answers
    current_question.answers.correct
  end

  def time_out?
    created_at + test.time_limit < Time.current
  end

  def next_question
    if current_question.nil?
      test.questions.first
    else
      test.questions.order(:id).where('id > ?', current_question.id).first
    end
  end
end

app/controllers/results_controller.rb
class ResultsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_result, only: %i[show result update]

  def show; end

  def result; end

  def update
    @result.accept!(params[:answer_ids])

    if @result.complited?
      if @result.successful? && CheckAchievementSpecifications.new(@result).create_achievements
        flash[:success] = t('.achieve')
      end
      redirect_to result_result_path(@result)
    else
      render :show
    end
  end

  private

  def set_result
    @result = Result.find(params[:id])
  end
end

app/helpers/results_helper.rb
module ResultsHelper
  def output_result(result)
    html_str = if result.successful?
                 "You passed the test!<br>
                 Your result is <div class = 'text-success' style = 'display: inline-block'>"
               else
                 " You failed the test!<br>
                  Your result is <div class = 'text-danger' style = 'display: inline-block'>"
               end
    html_str.concat(result.percentage_result.to_s, "<\/div>", ' %').html_safe
  end

  def get_progress(result)
    (result.number_question - 1) * 100 / result.test.questions.count
  end
end

app/views/results/result.html.erb
<h1> <%= t('.header', title: @result.test.title) %></h1>

<%= output_result(@result) %> 

app/views/results/show.html.erb
<h1><%= t('.header', title: @result.test.title) %></h1>
<b><strong>
  <%= t('.questions', count: @result.test.questions.count) %>
</b></strong>

<p>
  <b>
    <%= t('.question', number: @result.number_question) %><br>
    <i><%= @result.current_question.body %></i>
  </b>
</p>

<%= form_with url: result_path(@result), local: true, method: :put, class: "result" do |form| %>
  <%= form.collection_check_boxes :answer_ids, @result.current_question.answers, :id, :body, include_hidden: false do |b| %>
    <p>
      <%= b.check_box id: "answer_ids_#{b.object.id}" %>
      <%= b.label %>
    </p>
  <% end %>

  <p><%= link_to  "Gist Question", gists_path(result: @result.id), method: :post %></p>
  <p><%= form.submit t('.next')%></p>
<% end %>

<div class="conteiner-bar">
  <div class="progressbar"><%= get_progress(@result) %>% </div>
</div>

<% if !@result.time_limit.zero?%>
  <p>
    <%= hidden_field_tag :time_left,  @result.time_left %>
    <%= hidden_field_tag :time_limit,  @result.time_limit %>
    Time left:<h2><span class="badge bg-secondary countdown">00:00</span></h2>
  </p>

  <div class="progress mt-3">
    <div class="progress-bar bg-success" style="width: 0%">100%</div>
  </div>
<% end %>