config/routes.rb
# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'users/registrations', sessions: 'users/sessions' }

  devise_scope :user do
    get '/users', to: 'devise/registrations#new'
    get '/users/password', to: 'devise/passwords#new'
  end

  root 'tests#index'

  # devise_for :users, path: :gurus, path_names: { sign_in: :login, sign_out: :logout }

  resources :tests, only: :index do
    resources :questions, shallow: true, only: :show do
      resources :answers, shallow: true, only: :show
    end

    member do
      post :start
    end
  end

  resources :results, only: %i[show update] do
    member do
      get :result
    end
  end

  resources :gists, only: :create

  namespace :admin do
    resources :tests do
      patch :update_inline, on: :member
      resources :questions, shallow: true, except: %i[index] do
        resources :answers, shallow: true, except: %i[index]
      end
    end
    resources :gists, only: :index

    resources :badges, except: %i[show]

    resources :achievements, only: %i[index create new] do
      collection do
        get :show_user_achieved
      end
    end
  end

  resources :badges, only: %i[index]

  resources :feedbacks, only: %i[new create]

  resources :achievements, only: :index
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :question

  validates :body, presence: true
  validate :validate_range, on: :create

  scope :correct, -> { where(correct: true) }

  private

  def validate_range
    errors.add(:base, 'Must be only 1 - 4 answers') if question.answers.count >= 4
  end
end

app/controllers/admin/answers_controller.rb
class Admin::AnswersController < Admin::BaseController
  before_action :find_question, only: %i[new create]
  before_action :set_answer, only: %i[show edit update destroy]

  def show; end

  def new
    @answer = Answer.new
  end

  def edit; end

  def create
    @answer = @question.answers.build(answer_params)

    if @answer.save
      redirect_to admin_answer_path(@answer)
      flash[:notice] = "Answer '#{@answer.body[0..30]}' was created"
    else
      render :new
    end
  end

  def update
    if @answer.update(answer_params)
      flash[:notice] = "Answer '#{@answer.body[0..30]}' was updated"
      redirect_to admin_answer_path(@answer)
    else
      render :edit
    end
  end

  def destroy
    @answer.destroy
    flash[:notice] = "Answer '#{@answer.body[0..30]}' was deleted"
    redirect_to admin_question_path(@answer.question)
  end

  private

  def find_question
    @question = Question.find(params[:question_id])
  end

  def set_answer
    @answer = Answer.find(params[:id])
  end

  def answer_params
    params.require(:answer).permit(:body, :correct)
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/views/admin/answers/_answer.html.erb
<li>
  <%= answer.body %><br>
  <%= link_to t('nav.show'), admin_answer_path(answer) %>
  <%= link_to t('nav.edit'), edit_admin_answer_path(answer) %>
  <%= link_to t('nav.del'), 
              admin_answer_path(answer), 
              method: :delete, 
              data: { confirm: 'Are you sure?' } %>
  </li>

app/views/admin/answers/_form.html.erb
<%= form_with model: [:admin, @question, @answer], local: true do |form| %>
  <%= render 'shared/errors', resource: @answer %>
    <p>
      <%= form.label :body %><br>
      <%= form.text_area :body, id: :answer_body, rows: 6, cols:60 %>
    </p>

    <p>
      <%= form.label :correct %>
      <%= form.check_box :correct, id: :answer_correct %>
    </p>

    <%= form.submit %>
<% end %>

app/views/admin/answers/edit.html.erb
<h1><%= t('.header') %> </h1>

<p>
  <%= @answer.question.body%>
</p>

<%= render 'form' %>

<%= link_to t('nav.back'), admin_question_path(@answer.question) %>

app/views/admin/answers/new.html.erb
<h1> <%= t('.new') %></h1>

<p><%= t('.question') %>: <%= @question.body%></p>

<%= render 'form' %>
<%= link_to t('nav.back'), admin_question_path(@question) %>

app/views/admin/answers/show.html.erb
<h1><%= t('.question') %></h1>


<p>
  <%= @answer.question.body%>
</p>

<p>
  <b><%= t('.answer') %></b>
  <%= @answer.body%>
</p>

<p>
  <b><%= t('.correct')%> :</b>
  <%= @answer.correct%>
</p>

<%= link_to t('nav.create'), new_admin_question_answer_path(@answer.question) %> |
<%= link_to t('nav.edit'), edit_admin_answer_path(@answer) %> |
<%= link_to t('nav.back'), admin_question_path(@answer.question) %>